package com.hskj.meettingsys.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hskj.meettingsys.bean.MqttMeetingListBean;

import com.hskj.meettingsys.greendao.MqttMeetingListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mqttMeetingListBeanDaoConfig;

    private final MqttMeetingListBeanDao mqttMeetingListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mqttMeetingListBeanDaoConfig = daoConfigMap.get(MqttMeetingListBeanDao.class).clone();
        mqttMeetingListBeanDaoConfig.initIdentityScope(type);

        mqttMeetingListBeanDao = new MqttMeetingListBeanDao(mqttMeetingListBeanDaoConfig, this);

        registerDao(MqttMeetingListBean.class, mqttMeetingListBeanDao);
    }
    
    public void clear() {
        mqttMeetingListBeanDaoConfig.clearIdentityScope();
    }

    public MqttMeetingListBeanDao getMqttMeetingListBeanDao() {
        return mqttMeetingListBeanDao;
    }

}
